In [15]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [16]:
data = pd.read_csv("C://Users//DELL//PycharmProjects//PythonProject_practice_2025//Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [17]:
# Preprocess the data
data = data.drop(['RowNumber','CustomerId','Surname'], axis = 1)

In [18]:
# Encode Categorical variables

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [19]:

onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')

geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()

geo_encoder_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)

geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [20]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis =1)
data.head(10)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

In [21]:
# split data into features and target
X = data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [22]:
# save the encoder and scaler for later use
with open('label_encoder_gender_reg.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo_reg.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [23]:
## split the data in training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
with open('scaler_reg.pkl', 'wb') as file:
    pickle.dump(scaler, file)

ANN Regression problem

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime

WARNING:tensorflow:From C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [27]:
model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)), ## HL1 connected with input layer
    Dense(32, activation = 'relu'), ## HL2
    Dense(1) ## output layer - when we don't apply any activation function the default activation function will be linear activation function
])

## compile the model

model.compile(optimizer = "adam", loss = 'mean_absolute_error', metrics=['mae'])

model.summary()

WARNING:tensorflow:From C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
## setup the Tensorboard

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq = 1)

In [29]:
## setup early stopping

early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, restore_best_weights = True)

In [30]:
## Training the model

history = model.fit(
    X_train, y_train, validation_data = (X_test, y_test), epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 7ms/step - loss: 100380.8750 - mae: 100380.8750 - val_loss: 98524.1094 - val_mae: 98524.1094
Epoch 2/100
250/250 [==============================] - 2s 6ms/step - loss: 99648.3672 - mae: 99648.3672 - val_loss: 97031.6797 - val_mae: 97031.6797
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 97067.7891 - mae: 97067.7891 - val_loss: 93225.3125 - val_mae: 93225.3125
Epoch 4/100
250/250 [==============================] - 2s 9ms/step - loss: 91980.2500 - mae: 91980.2500 - val_loss: 86845.8906 - val_mae: 86845.8906
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 84535.3984 - mae: 84535.3984 - val_loss: 78587.4609 - val_mae: 78587.4609
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 75743.3359 - mae: 75743.3359 - val_loss: 69964.4453 - val_mae: 69964.4453
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 67081.3359 - mae: 67081.3359 - val_loss: 62241.1914 - val_mae: 62241.1914
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 59927.3398 - mae: 59927.3398 - val_loss: 56529.7930 - val_mae: 56529.7930
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 55211.0508 - mae: 55211.0508 - val_loss: 53224.2227 - val_mae: 53224.2227
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 52571.6523 - mae: 52571.6523 - val_loss: 51694.3984 - val_mae: 51694.3984
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 51318.5078 - mae: 51318.5078 - val_loss: 51099.1641 - val_mae: 51099.1641
Epoch 12/100
250/250 [==============================] - 3s 11ms/step - loss: 50731.7344 - mae: 50731.7344 - val_loss: 50866.6758 - val_mae: 50866.6758
Epoch 13/100
250/250 [==============================] - 1s 5ms/step - loss: 50478.2812 - mae: 50478.2812 - val_loss: 50773.6211 - val_mae: 50773.6211
Epoch 14/100
250/250 [==============================] - 2s 6ms/step - loss: 50346.4766 - mae: 50346.4766 - val_loss: 50713.4922 - val_mae: 50713.4922
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 50258.4336 - mae: 50258.4336 - val_loss: 50656.1172 - val_mae: 50656.1172
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 50187.5430 - mae: 50187.5430 - val_loss: 50615.7891 - val_mae: 50615.7891
Epoch 17/100
250/250 [==============================] - 1s 5ms/step - loss: 50126.6992 - mae: 50126.6992 - val_loss: 50566.5781 - val_mae: 50566.5781
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 50079.8750 - mae: 50079.8750 - val_loss: 50528.3867 - val_mae: 50528.3867
Epoch 19/100
250/250 [==============================] - 1s 5ms/step - loss: 50035.5781 - mae: 50035.5781 - val_loss: 50504.0547 - val_mae: 50504.0547
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 49996.8633 - mae: 49996.8633 - val_loss: 50479.4805 - val_mae: 50479.4805
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 49960.8750 - mae: 49960.8750 - val_loss: 50471.0625 - val_mae: 50471.0625
Epoch 22/100
250/250 [==============================] - 1s 5ms/step - loss: 49929.1953 - mae: 49929.1953 - val_loss: 50452.5586 - val_mae: 50452.5586
Epoch 23/100
250/250 [==============================] - 1s 5ms/step - loss: 49899.0430 - mae: 49899.0430 - val_loss: 50437.8711 - val_mae: 50437.8711
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 49868.8047 - mae: 49868.8047 - val_loss: 50412.3945 - val_mae: 50412.3945
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49844.9531 - mae: 49844.9531 - val_loss: 50398.1211 - val_mae: 50398.1211
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49822.6367 - mae: 49822.6367 - val_loss: 50381.1914 - val_mae: 50381.1914
Epoch 27/100
250/250 [==============================] - 2s 6ms/step - loss: 49802.0625 - mae: 49802.0625 - val_loss: 50379.1602 - val_mae: 50379.1602
Epoch 28/100
250/250 [==============================] - 2s 6ms/step - loss: 49780.1797 - mae: 49780.1797 - val_loss: 50374.3672 - val_mae: 50374.3672
Epoch 29/100
250/250 [==============================] - 1s 4ms/step - loss: 49760.5430 - mae: 49760.5430 - val_loss: 50366.0664 - val_mae: 50366.0664
Epoch 30/100
250/250 [==============================] - 2s 7ms/step - loss: 49743.4883 - mae: 49743.4883 - val_loss: 50352.9375 - val_mae: 50352.9375
Epoch 31/100
250/250 [==============================] - 2s 7ms/step - loss: 49729.5547 - mae: 49729.5547 - val_loss: 50351.2383 - val_mae: 50351.2383
Epoch 32/100
250/250 [==============================] - 2s 6ms/step - loss: 49710.8555 - mae: 49710.8555 - val_loss: 50349.5703 - val_mae: 50349.5703
Epoch 33/100
250/250 [==============================] - 1s 5ms/step - loss: 49695.9766 - mae: 49695.9766 - val_loss: 50342.0938 - val_mae: 50342.0938
Epoch 34/100
250/250 [==============================] - 1s 5ms/step - loss: 49683.7773 - mae: 49683.7773 - val_loss: 50342.1445 - val_mae: 50342.1445
Epoch 35/100
250/250 [==============================] - 1s 5ms/step - loss: 49670.0234 - mae: 49670.0234 - val_loss: 50333.2891 - val_mae: 50333.2891
Epoch 36/100
250/250 [==============================] - 3s 10ms/step - loss: 49658.1836 - mae: 49658.1836 - val_loss: 50331.6641 - val_mae: 50331.6641
Epoch 37/100
250/250 [==============================] - 1s 5ms/step - loss: 49644.6172 - mae: 49644.6172 - val_loss: 50332.4766 - val_mae: 50332.4766
Epoch 38/100
250/250 [==============================] - 1s 6ms/step - loss: 49634.7578 - mae: 49634.7578 - val_loss: 50328.3750 - val_mae: 50328.3750
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49625.1680 - mae: 49625.1680 - val_loss: 50327.0117 - val_mae: 50327.0117
Epoch 40/100
250/250 [==============================] - 1s 6ms/step - loss: 49615.9766 - mae: 49615.9766 - val_loss: 50331.9336 - val_mae: 50331.9336
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 49603.4492 - mae: 49603.4492 - val_loss: 50319.6133 - val_mae: 50319.6133
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 49595.1914 - mae: 49595.1914 - val_loss: 50322.5625 - val_mae: 50322.5625
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 49586.9219 - mae: 49586.9219 - val_loss: 50325.2969 - val_mae: 50325.2969
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 49579.6406 - mae: 49579.6406 - val_loss: 50328.6445 - val_mae: 50328.6445
Epoch 45/100
250/250 [==============================] - 2s 6ms/step - loss: 49572.8438 - mae: 49572.8438 - val_loss: 50332.3594 - val_mae: 50332.3594
Epoch 46/100
250/250 [==============================] - 1s 5ms/step - loss: 49562.8633 - mae: 49562.8633 - val_loss: 50329.4023 - val_mae: 50329.4023
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49555.0352 - mae: 49555.0352 - val_loss: 50321.4648 - val_mae: 50321.4648
Epoch 48/100
250/250 [==============================] - 1s 4ms/step - loss: 49548.1836 - mae: 49548.1836 - val_loss: 50327.1953 - val_mae: 50327.1953
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49540.5078 - mae: 49540.5078 - val_loss: 50328.0117 - val_mae: 50328.0117
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49533.2109 - mae: 49533.2109 - val_loss: 50321.3398 - val_mae: 50321.3398
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49528.9922 - mae: 49528.9922 - val_loss: 50321.1992 - val_mae: 50321.1992

In [31]:
## load tensorboard extention

%load_ext tensorboard

In [32]:
%tensorboard --logdir regressionlogs/fit

In [34]:
## Evaluate model on the test data

test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Mae : {test_mae}')
print(f'Test loss: {test_loss}')

63/63 [==============================] - 0s 5ms/step - loss: 50319.6133 - mae: 50319.6133
Test Mae : 50319.61328125
Test loss: 50319.61328125

In [35]:
model.save('regression_model.h5')

C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(